# Çoklu Doğrusal regrasyon

In [1]:
import pandas as pd
df=pd.read_csv("Advertising.csv",usecols=[1,2,3,4])
df.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [4]:
x=df.drop("sales",axis=1)
#bagımsız değişkenleri seçme işlemi gerçekleştirdik

In [5]:
x[0:10]

TV  radio  newspaper
0  230.1   37.8       69.2
1   44.5   39.3       45.1
2   17.2   45.9       69.3
3  151.5   41.3       58.5
4  180.8   10.8       58.4
5    8.7   48.9       75.0
6   57.5   32.8       23.5
7  120.2   19.6       11.6
8    8.6    2.1        1.0
9  199.8    2.6       21.2

In [20]:
x=sm.add_constant(x)
#sabit katsayı eklemesi yapıldı

In [21]:
y=df[["sales"]]
#bagımlı degişkeni aldık.

In [22]:
y.head()

sales
0   22.1
1   10.4
2    9.3
3   18.5
4   12.9

In [23]:
from sklearn.model_selection import train_test_split,cross_val_predict,cross_val_score
#train_test_split=test ve train için,cross_val_predict=tahmin edilen degerler için,cross_val_score=valudeişin score için aldık

In [24]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
#train ve test ayırma için,%20 lik test için,farklı degerler çıkmasını istemedigimiz için random kullandık

In [25]:
x_train

const     TV  radio  newspaper
79     1.0  116.0    7.7       23.1
197    1.0  177.0    9.3        6.4
38     1.0   43.1   26.7       35.1
24     1.0   62.3   12.6       18.3
122    1.0  224.0    2.4       15.6
..     ...    ...    ...        ...
106    1.0   25.0   11.0       29.7
14     1.0  204.1   32.9       46.0
92     1.0  217.7   33.5       59.0
179    1.0  165.6   10.0       17.6
102    1.0  280.2   10.1       21.4

[160 rows x 4 columns]

In [26]:
y_test.shape

(40, 1)

In [27]:
y_train[0:10]

sales
79    11.0
197   12.8
38    10.1
24     9.7
122   11.6
195    7.6
29    10.5
19    14.6
143   10.4
86    12.0

In [28]:
training=df.copy()

In [29]:
training.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

# Çoklu dog. reg. model kurulumu

In [30]:
import statsmodels.api as sm

In [31]:
lm=sm.OLS(y_train,x_train)
model=lm.fit()
model.summary()
#model kurulum işlemi gerçekleştirdik

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  sales   R-squared:                       0.896
Model:                            OLS   Adj. R-squared:                  0.894
Method:                 Least Squares   F-statistic:                     446.6
Date:                Thu, 02 May 2024   Prob (F-statistic):           2.53e-76
Time:                        14:28:46   Log-Likelihood:                -306.64
No. Observations:                 160   AIC:                             621.3
Df Residuals:                     156   BIC:                             633.6
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          2.9791      0.354      8.427      0.000       2.281       3.677
TV             0.0447      0.002     28.544      0.000       0.042       0.048
radio          0.1892      0.010     19.518      0.000       0.170       0.208
newspaper      0.0028      0.007      0.392      0.696      -0.011       0.017
==============================================================================
Omnibus:                       67.697   Durbin-Watson:                   2.161
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              240.326
Skew:                          -1.627   Prob(JB):                     6.52e-53
Kurtosis:                       8.046   Cond. No.                         471.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [ ]:
model.summary().tables[1]

In [36]:
model.params

const        2.979067
TV           0.044730
radio        0.189195
newspaper    0.002761
dtype: float64

# sklearn ile model kurma

In [37]:
from sklearn.linear_model import LinearRegression

In [41]:
lm=LinearRegression()
model1=lm.fit(x_train,y_train)

In [42]:
model1.intercept_

array([2.97906734])

In [44]:
model1.coef_

array([[0.        , 0.04472952, 0.18919505, 0.00276111]])

In [47]:
model1.predict(x_train)[0:10]

array([[ 9.68827502],
       [12.67337707],
       [10.0553326 ],
       [ 8.20010235],
       [13.49562077],
       [ 5.42585998],
       [ 9.2767456 ],
       [14.14222434],
       [ 8.83116901],
       [11.63897134]])

# Çoklu reg. tahmin modeli

model denklemi:
Sales=2.97 + 0.045*TV + 0.18*radio + 0.002*newspaper

Örnegin 30 birim tv harcaması,10 birim radio harcamsı, 40 birimde gazete harcamsı oldugunda satışların  tahmini degeri ne olur?

In [57]:
yeni_veri=[[0],[30],[10],[40]]
yeni_veri=pd.DataFrame(yeni_veri).T

In [66]:
model.predict(yeni_veri)

C:\Users\alper\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[6.32334798]])

In [60]:
from sklearn.metrics import mean_squared_error,r2_score

In [61]:
import numpy as np

In [63]:
rmse=np.sqrt(mean_squared_error(y_train,model.predict(x_train)))

In [64]:
rmse
#egitim hatasını bulduk

1.644727765644337

In [65]:
rmse=np.sqrt(mean_squared_error(y_test,model.predict(x_test)))

In [68]:
rmse
#test hatasını bulduk

1.781599661533451

# Model tuning/model doğrulama

In [69]:
df.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [70]:
x=df.drop("sales",axis=1)
y=df["sales"]
x=sm.add_constant(x)

In [74]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=66)
lm=LinearRegression()
model=lm.fit(x_train,y_train)

In [75]:
np.sqrt(mean_squared_error(y_train,model.predict(x_train)))
#eğitim hatası

1.615944117920615

In [76]:
model.score(x_train,y_train)
#test hatası

0.8985647494060172

In [78]:
cross_val_score(model,x,y,cv=10,scoring="r2")
#birbirinden farklı r kare degeri

array([0.87302696, 0.8581613 , 0.92968723, 0.89013272, 0.93146498,
       0.93138735, 0.7597901 , 0.91217097, 0.83891753, 0.92882311])

In [80]:
cross_val_score(model,x_train,y_train,cv=10,scoring="r2").mean()
#daha güvenilir r kare degeridir

0.8687394608304275

In [85]:
np.sqrt(-cross_val_score(model,
                x_train,
                y_train,
                cv=10,
                scoring="neg_mean_squared_error"))
#eğitim seti için 10 adet eğitim hatası oluştu

array([2.20128031, 1.78711127, 1.88926933, 1.2005998 , 1.55000863,
       1.21004315, 1.33471864, 1.8559155 , 1.91627131, 1.57966626])

In [88]:
np.sqrt(-cross_val_score(model,
                x_test,
                y_test,
                cv=10,
                scoring="neg_mean_squared_error")).mean()
#gerçek eğitim hatası

1.7347388129981092

In [89]:
np.sqrt(mean_squared_error(y_test,model.predict(x_test)))

1.877348118434005